In [7]:
# Data

company_detail_list = [
      {
          'name': 'Company 1',
          'domain': 'Retail',
          'country': 'United States'
      },
      {
          'name': 'Company 2',
          'domain': 'Technology',
          'country': 'United Kingdom'
      },
      {
          'name': 'Company 3',
          'domain': 'Healthcare',
          'country': 'United States'
      }
  ]

employee_detail_list = [
     {
          'name': 'EMP-0001',
          'first_name': 'John',
          'last_name': 'Doe',
          'full_name': 'John Doe',
          'company': 'Company 1',
          'nationality': 'Australia'
      },
      {
          'name': 'EMP-0002',
          'first_name': 'Tom',
          'last_name': 'Smith',
          'full_name': 'Tom Smith',
          'company': 'Company 2',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0003',
          'first_name': 'Andrew',
          'last_name': 'Sebastian',
          'full_name': 'Andrew Sebastian',
          'company': 'Company 3',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0005',
          'first_name': 'Ying Han',
          'last_name': 'Tan',
          'full_name': 'Ying Han Tan',
          'company': 'Company 1',
          'nationality': 'Australia'
      },
      {
          'name': 'EMP-0015',
          'first_name': 'Kenneth',
          'last_name': 'Ng',
          'full_name': 'Kenneth Ng',
          'company': 'Company 3',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0018',
          'first_name': 'Rubby',
          'last_name': 'Lee',
          'full_name': 'Rubby Lee',
          'company': 'Company 2',
          'nationality': 'Hong Kong'
      },
     {
          'name': 'EMP-0017',
          'first_name': 'Robert',
          'last_name': 'White',
          'full_name': 'Robert White',
          'company': 'Company 1',
          'nationality': 'United Kingdom'
      }
  ]

In [11]:
def get_employees_with_company_country(company_detail_list, employee_detail_list):
 
    company_nationality_count = {}

    for employee in employee_detail_list:
        company = employee['company']
        nationality = employee['nationality']

        if company not in company_nationality_count:
            company_nationality_count[company] = {}
        
   
        if nationality not in company_nationality_count[company]:
            company_nationality_count[company][nationality] = 0
        
       
        company_nationality_count[company][nationality] += 1

 
    result = []
    for company in company_nationality_count:
        result.append({
            "company": company,
            "employee_nationality": company_nationality_count[company]
        })

    return result


result = get_employees_with_company_country(company_detail_list, employee_detail_list)
print(json.dumps(result, indent=4))

[
    {
        "company": "Company 1",
        "employee_nationality": {
            "Australia": 2,
            "Hong Kong": 1
        }
    },
    {
        "company": "Company 2",
        "employee_nationality": {
            "Hong Kong": 1,
            "United States": 1
        }
    },
    {
        "company": "Company 3",
        "employee_nationality": {
            "United States": 2
        }
    }
]